FROM apache/airflow:2.8.3-python3.8
COPY requirements.txt requirements-airflow.txt requirements-test.txt ./
USER root
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    libleveldb-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /opt/airflow
COPY dags ./dags
COPY tests ./tests
COPY data ./data
COPY entrypoint.sh ./
RUN chmod +x entrypoint.sh
RUN chmod -R 777 .
USER airflow
RUN pip install --no-cache-dir --user -r requirements.txt -r requirements-test.txt -r requirements-airflow.txt
