name: Build and Test
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

env:
  AIRFLOW_HOME: /home/runner/work/airflow-dags/airflow-dags
  IMAGE_NAME: airflow-dags-test

jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v3

      - name: Checkout PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.16

      - name: Install python dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir --upgrade setuptools
          pip install --no-cache-dir --upgrade wheel
          pip install -r requirements.txt -r requirements-test.txt -r requirements-airflow.txt

      - name: Run services on docker compose
        run: docker compose up -d postgres redis sftp ftp s3 create_buckets

      - name: List services for IT Tests
        run: docker ps

      - name: List all dags
        run: airflow dags list

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.test
          tags: ${{ env.IMAGE_NAME }}:latest
          push: false
          load: true

      - name: List Docker Images
        run: docker images

      - name: List services for IT Tests
        run: docker ps

      - name: Run Pytest in Docker
        run: docker run --name workflows --network=host --entrypoint pytest ${{ env.IMAGE_NAME }}:latest tests
